name: flutter_tools
description: Flutter工具箱，提供基本的第三方库的使用，可用于项目基础框架
author: ganyizhi
homepage: https://github.com/ganzi01234

version: 1.0.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #IOS风格
  cupertino_icons: ^0.1.2
  event_bus: ^1.0.1
  #路径路由
  fluro: ^1.3.4
  #拍照或者本地读取照片
  image_picker: ^0.6.0+1
  sqflite: ^1.1.5
  #调用SMS或EMAIL等Intent功能
  url_launcher: ^5.1.2
  # 本地存储、收藏功能
  shared_preferences: ^0.4.3
  flutter_spinkit: "^3.1.0"
  #基础库
  dio: ^2.0.15
  #WebView
  flutter_webview_plugin: ^0.3.4
  cookie_jar: ^1.0.0
  # 日期格式化
  intl: 0.15.7
  #日期控件
  city_pickers: ^0.0.1
#  flutter_bloc: ^0.11.1
#  bloc: ^0.12.0
  html: ^0.14.0+2
  #下载文件
  flutter_downloader: ^1.1.7
  #还没研究
  path_provider: ^1.1.0
  #权限相关
  permission: ^0.1.2
  #还没研究
  open_file: ^2.0.1+2
  #包信息
  package_info: ^0.4.0+3
  #设备信息
  device_info : ^0.2.0
  #录音的package
  audio_recorder: any #录音、播放
  flutter_sound: ^1.1.5 #录音
  #谷歌相关API
  googleapis: any
  googleapis_auth: any
  flutter_toolslib:
    path: ./flutter_toolslib/
  #baidumap百度地图
  fm_baidu_map: ^0.0.7
  #字体适配 只在百度map使用
  fm_fit: ^0.0.2
  #翻译
  translator: ^0.1.2
  #阿里支付
  flutter_alipay: ^0.1.0
  #微信SDK
  flutter_wechat: ^0.1.5
  #上下拉刷新
  flutter_easyrefresh: ^2.0.2
  #二维码和条形码扫描
  flutter_mobile_vision_jamel: ^1.0.0
  #获得UUID
  uuid: ^2.0.1
  #广告插件
#  admob_flutter: "^0.3.1"
  firebase_admob: ^0.9.0+3
  #游戏相关包
  provider: ^2.0.0
  flare_flutter: ^1.5.5
  auto_size_text: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
  - assets/app.db
  - assets/images/
  - assets/fonts/
  - assets/style_sphinx/
  - assets/images/
  - assets/images/2.0x/
  - assets/images/3.0x/
  - assets/flare/
  - assets/docs/code_chomper_alpha.dart
  - assets/docs/code_chomper_beta.dart

  fonts:
  - family: FlamanteRoma
    fonts:
    - asset: assets/fonts/Flamante-Roma-Medium.ttf
    - asset: assets/fonts/Flamante-Roma-MediumItalic.ttf

  - family: LatoBold
    fonts:
    - asset: assets/fonts/Lato-Bold.ttf
  - family: SpaceMonoRegular
    fonts:
    - asset: assets/fonts/SpaceMono-Regular.ttf
  - family: SpaceMonoBold
    fonts:
    - asset: assets/fonts/SpaceMono-Bold.ttf
  - family: RobotoCondensedBold
    fonts:
    - asset: assets/fonts/RobotoCondensed-Bold.ttf
  - family: RobotoRegular
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
  - family: MontserratMedium
    fonts:
      - asset: assets/fonts/Montserrat-Medium.otf
  - family: MontserratRegular
    fonts:
      - asset: assets/fonts/Montserrat-Regular.otf
  - family: MontserratBold
    fonts:
      - asset: assets/fonts/Montserrat-Bold.otf
